name: PHP 8.5
on: push

jobs:
  build:
    name: Static analysis, unit tests, and linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ./vendor
          key: composer-${{ runner.os }}-8.5

      - name: Install dependencies
        run: |
          composer install

      - name: Run PHPStan
        run: |
          ./vendor/bin/phpstan

      - name: PHP Code Sniffer
        run: |
          ./vendor/bin/phpcs

      - name: Run PHPUnit
        run: |
          ./vendor/bin/phpunit